
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=thanos
      - POSTGRES_PASSWORD=changeme
      - POSTGRES_DB=movies
    ports:
      - '5432:5432'